-- All the net messages defined here
util.AddNetworkString("nosay_msg")
util.AddNetworkString("nosay_admin_ui")
util.AddNetworkString("nosay_admin_network_setting")
util.AddNetworkString("nosay_admin_settings_update")
util.AddNetworkString("nosay_admin_words_add")
util.AddNetworkString("nosay_admin_words_remove")
util.AddNetworkString("nosay_admin_lookupid")
util.AddNetworkString("nosay_admin_lookupid_remove")
util.AddNetworkString("nosay_admin_lookupid_return")
util.AddNetworkString("nosay_admin_network_word")
util.AddNetworkString("nosay_admin_network_word_remove")
util.AddNetworkString("nosay_admin_inital_settings")
util.AddNetworkString("nosay_admin_inital_words")
