ITEM.name = "Exotic Case"
ITEM.desc = "A small one of a kind exotic box typically used to present wedding rings and objects of great value to another person of even greater value."
ITEM.width = 1
ITEM.height = 1
ITEM.invWidth = 1
ITEM.invHeight = 1
ITEM.category = "Storage"
ITEM.flag = "v"
ITEM.model = "models/ring_box_holder.mdl"
ITEM.uniqueID = "stor_ringcase"
