player_manager.AddValidModel("NCR Trooper [M]", "models/player/yates/ncrtrooper.mdl")
player_manager.AddValidModel("NCR Trooper [F]", "models/player/yates/ncrtrooperf.mdl")
player_manager.AddValidModel("NCR Medic [M]", "models/player/yates/ncrmedic.mdl")
player_manager.AddValidModel("NCR Medic [F]", "models/player/yates/ncrmedicf.mdl")
player_manager.AddValidModel("NCR Officer [M]", "models/player/yates/ncrofficer.mdl")
player_manager.AddValidModel("NCR Officer [F]", "models/player/yates/ncrofficerf.mdl")
player_manager.AddValidModel("NCR Ranger [M]", "models/player/yates/rangercombat.mdl")
player_manager.AddValidModel("NCR Ranger [F]", "models/player/yates/rangercombatf.mdl")
player_manager.AddValidModel("NCR HIC [M]", "models/player/yates/ncrpa.mdl")
player_manager.AddValidModel("NCR HIC [F]", "models/player/yates/ncrpaf.mdl")
player_manager.AddValidModel("Scribe [M]", "models/player/yates/scribe.mdl")
player_manager.AddValidModel("Scribe [F]", "models/player/yates/scribef.mdl")
