Marketplace.Config.Tax = 10 -- % Tax taken from each sale
Marketplace.Config.Slots = 10 -- How many active listings a user can have at a time
Marketplace.Config.MinimumPrice = 2 -- The minimum price of an item
Marketplace.Config.MaximumPrice = 2147483647 -- The maximum price of an item, this must not exceed 2147483647
Marketplace.Config.MarketModel = "models/maxib123/controlpanel.mdl" -- Model of the market entity
Marketplace.Config.RemoteMarketplaceURL = "http://claymoregaming.com/marketplace.php"
Marketplace.Config.CurrencyPrefix = ""
Marketplace.Config.CurrencySuffix = " caps"
Marketplace.Config.LogoURL = "https://i.imgur.com/CAhGigj.png"
Marketplace.Config.Blacklist = { -- Items in this list will be impossible to list on the market
	["stor_briefcase"] = true, -- Small backpack (Storage Item)
	["stor_briefcasemedium"] = true, -- Medium backpack (Storage Item)
	["stor_briefcaselarge"] = true,  -- Large backpack (Storage Item)
	["stor_ringcase"] = true, -- Ring Case (Storage Item)
	["holotape"] = true, -- Holotape
	["book"] = true, -- Holotape
	-- Enclave Items --
	["armor_X-02"] = true, -- X-02 Enclave Power Armor
	["armor_X-02_nco"] = true, -- X-02 Enclave NCO Power Armor
	["armor_tesla"] = true, -- X-02 Tesla Enclave Power Armor
	["armor_X-03"] = true, -- X-02 Hellfire Enclave Power Armor
	["armor_X-RE"] = true, -- X-01 Richardson Elite Power Armor MKI
	["armor_enclaveofficer"] = true, -- X-01 Richardson Elite Power Armor MKI
	["enclavescientistoutfit"] = true, -- Enclave Biosuit
	["armor_enclavesec"] = true, -- Enclave Combat Armor (Legacy)
	["armor_colonel"] = true, -- Enclave Commander Uniform (Legacy)
	["armor_remnant"] = true, -- Enclave X-01 Navarro Power Armor (Legacy)
	["armor_remnant-ganon"] = true, -- Enclave X-01 Tesla Navarro Power Armor (Legacy)
	["armor_x-03mod"] = true, -- Modified Hellfire Power Armor (Legacy)
	["enclave_officer_hat"] = true, -- Enclave Officer Hat
	["x02pahelmet"] = true, -- X-02 Enclave Power Armor Helmet
	["x02pahelmet_nco"] = true, -- X-02 Enclave NCO Power Armor Helmet
	["x02teslapahelmet"] = true, -- X-02 Enclave Tesla Power Armor Helmet
	["x03hellfirepahelmet"] = true, -- X-03 Enclave Hellfire Power Armor Helmet
	["advancedpowerarmorhelmet"] = true, -- X-01 Richardson Elite Power Armor Helmet
	["enclavegaussrifle"] = true, -- Enclave Gauss Rifle
	["weapon_enclave_laserrifle"] = true, -- Enclave Laser Rifle
	["weapon_enclave_gatlinglaser"] = true, -- Enclave Gatling Laser
	["weapon_enclave_plasmarifle"] = true, -- Enclave Plasma Rifle
	["weapon_enclave_multiplasrifle"] = true, -- Enclave Multi Plasma Rifle
	["incinerator"] = true, -- (Enclave) Incinerator
}
Marketplace.Config.Categories = Marketplace.Config.Categories or {}
