nut.fallout.registry.drinks = {
/**	["water"] = {
		["name"] = "Purified Water",
		["desc"] = "An old carton taped together and filled with purified water.",
		["model"] = "models/fallout 3/water.mdl",
		["restore"] = 250,
		["rads"] = 0,
	},
	["dirtywater"] = {
		["name"] = "Dirty Water",
		["desc"] = "An old carton taped together and filled with dirty water.",
		["model"] = "models/props_junk/garbage_glassbottle002a.mdl",
		["restore"] = 200,
		["rads"] = 10,
	},
	["nukacola"] = {
		["name"] = "Nuka Cola",
		["desc"] = "A bottle of classic Nuka Cola.",
		["model"] = "models/nuka/nuka-pw.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["sunset"] = {
		["name"] = "Sunset Sarsaparilla",
		["desc"] = "An old carton taped together and filled with dirty water.",
		["model"] = "models/nuka/sunset.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukacolaquantum"] = {
		["name"] = "Nuka Cola Quantum",
		["desc"] = "A bottle of glowing Nuka Cola.",
		["model"] = "models/nuka/nuka-quantum.mdl",
		["restore"] = 1000,
		["rads"] = 50,
	},
	["nukacherry"] = {
		["name"] = "Nuka Cola Cherry",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/nuka/nuka-cherry.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukafusion"] = {
		["name"] = "Nuka Cola Fusion",
		["desc"] = "A bottle of glowing Nuka Cola.",
		["model"] = "models/maxib123/nukafusion.mdl",
		["restore"] = 100,
		["rads"] = 990,
	},
	["nukaberry"] = {
		["name"] = "Nuka Cola Berry",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/maxib123/nukacherry.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukaclear"] = {
		["name"] = "Nuka Cola Clear",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/maxib123/nukaclear.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukablack"] = {
		["name"] = "Nuka Cola Black",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/maxib123/nukacola.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukafrost"] = {
		["name"] = "Nuka Cola Frost",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/maxib123/nukafrost.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukaheat"] = {
		["name"] = "Nuka Cola Heat",
		["desc"] = "A bottle of hot Nuka Cola.",
		["model"] = "models/maxib123/nukaheat.mdl",
		["restore"] = 100,
		["rads"] = 25,
	},
	["nukaquartz"] = {
		["name"] = "Nuka Cola Quartz",
		["desc"] = "A bottle of flavored Nuka Cola.",
		["model"] = "models/maxib123/nukaquartz.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["Milk"] = {
		["name"] = "Milk",
		["desc"] = "A bottle of dirty milk.",
		["model"] = "models/milk/milk.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["nukavictory"] = {
		["name"] = "Nuka Cola Victory",
		["desc"] = "The rarest Nuka Cola ever produced",
		["model"] = "models/maxib123/nukavictory.mdl",
		["restore"] = 1000,
		["rads"] = 2,
	},
	["beer"] = {
		["name"] = "Beer",
		["desc"] = "A bottle perfect for crackin' open with the boys.",
		["model"] = "models/props_junk/garbage_glassbottle003a.mdl",
		["restore"] = 215,
		["rads"] = 6,
	},
	["wine"] = {
		["name"] = "Wine",
		["desc"] = "A bottle of pre-war wine.",
		["model"] = "models/props_junk/garbage_glassbottle001a.mdl",
		["restore"] = 300,
		["rads"] = 9,
	},
	["whiskey"] = {
		["name"] = "Whiskey",
		["desc"] = "A bottle of memory eraser.",
		["model"] = "models/maxib123/whiskey.mdl",
		["restore"] = 120,
		["rads"] = 8,
	},
	["owen"] = {
		["name"] = "Owen's Cum",
		["desc"] = "An incredibly rare easter-egg item. Only a fool would drink this.",
		["model"] = "models/milk/milk-pw.mdl",
		["restore"] = 1000,
		["rads"] = 50,
	},
	["keith"] = {
		["name"] = "Keith's Bleach",
		["desc"] = "An incredibly rare easter-egg item. Only a fool would drink this.",
		["model"] = "models/props_junk/garbage_plasticbottle001a.mdl",
		["restore"] = 1000,
		["rads"] = 1000,
	},
*/}
