nut.fallout.registry.foods = {
	["carrot"] = {
		["name"] = "Carrot",
		["desc"] = "A yellow appearing carrot with spouting roots and a leafy top.",
		["model"] = "models/fallout/consumables/carrot.mdl",
		["restore"] = 250,
		["rads"] = 5,
	},

	["mutfruit"] = {
		["name"] = "Mutfruit",
		["desc"] = "A purple looking fruit with bright yellow leaves, it looks yummy.",
		["model"] = "models/fallout/consumables/mutfruit.mdl",
		["restore"] = 250,
		["rads"] = 8,
	},
	["cram"] = {
		["name"] = "Cram",
		["desc"] = "Processed meat from before the War, found in blue cardboard boxes.",
		["model"] = "models/fallout 3/cram.mdl",
		["restore"] = 400,
		["rads"] = 7,
	},
	["dandyapples"] = {
		["name"] = "Dandy Apples",
		["desc"] = "Candied apples packaged in a red cardboard box.",
		["model"] = "models/fallout 3/dandy_apples.mdl",
		["restore"] = 200,
		["rads"] = 3,
	},
	["gum"] = {
		["name"] = "Gum",
		["desc"] = "A box of ancient chewing gum.",
		["model"] = "models/fallout 3/gum.mdl",
		["restore"] = 100,
		["rads"] = 2,
	},
	["rgum"] = {
		["name"] = "Radioactive Gum",
		["desc"] = "A box of glowing chewing gum.",
		["model"] = "models/fallout 3/gum_2.mdl",
		["restore"] = 100,
		["rads"] = 350,
	},
	["human"] = {
		["name"] = "Gourmet Meat",
		["desc"] = "Strange meat with a peculiar smell.",
		["model"] = "models/fallout 3/human_meat.mdl",
		["restore"] = 300,
		["rads"] = 10,
	},
	["animal"] = {
		["name"] = "Crispy Squirrel Bits",
		["desc"] = "It's probably squirrel...?",
		["model"] = "models/fallout 3/animal_bits.mdl",
		["restore"] = 350,
		["rads"] = 8,
	},
	["potato"] = {
		["name"] = "Potato",
		["desc"] = "A lonesome potato",
		["model"] = "models/fallout 3/potato.mdl",
		["restore"] = 260,
		["rads"] = 5,
	},
	/**["radroach"] = {
		["name"] = "Radroach Meat",
		["desc"] = "A lump of raw radroach meat.",
		["model"] = "models/fallout 3/radroach_meat.mdl",
		["restore"] = 300,
		["rads"] = 100,
	},**/
	["beans"] = {
		["name"] = "Beans",
		["desc"] = "A can of pre-war beans.",
		["model"] = "models/fallout 3/beans.mdl",
		["restore"] = 300,
		["rads"] = 6,
	},
	["apple"] = {
		["name"] = "Apple",
		["desc"] = "A lonesome apple.",
		["model"] = "models/fallout 3/apple_1.mdl",
		["restore"] = 200,
		["rads"] = 3,
	},
		["tarberry"] = {
		["name"] = "Tarberry",
		["desc"] = "A mutated berry that has evolved to grow in dirt.",
		["model"] = "models/fallout/consumables/tarberry.mdl",
		["restore"] = 150,
		["rads"] = 5,
	},
}
