nut.fallout.templates.laser = {
	["energy"] = {["component_steel"] = 3, ["component_plastic"] = 2, ["component_springs"] = 2, ["component_screws"] = 3, ["component_adhesive"] = 1, ["component_rubber"] = 1, ["component_fiberoptics"] = 2},
	["heavy"] = {["component_steel"] = 6, ["component_springs"] = 4, ["component_screws"] = 4, ["component_adhesive"] = 3, ["component_rubber"] = 1, ["component_fiberoptics"] = 5},
	["sidearm"] = {["component_steel"] = 1, ["component_plastic"] = 1, ["component_springs"] = 2, ["component_screws"] = 2, ["component_adhesive"] = 1, ["component_rubber"] = 1, ["component_fiberoptics"] = 1},
}

nut.fallout.registry.laser = {
/**	["weapon_laserriflescp"] = {
		["name"] = "Scoped Laser Rifle",
		["desc"] = "A laser rifle with an attached scope.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserriflescope.mdl",
		["class"] = "weapon_laserrifle_scoped_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},

	["weapon_tribeam"] = {
		["name"] = "Tribeam Laser Rifle",
		["desc"] = "A pre-war laser rifle fitted with a tri-beam splitter.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/tribeamlaserrifle.mdl",
		["class"] = "weapon_laser_tribeam",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 15,
	},

	["weapon_laserrifle"] = {
		["name"] = "Laser Rifle",
		["desc"] = "A standard, common issue pre-war laser rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_laserrifle_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},

	["weapon_laserpdw"] = {
		["name"] = "Recyling Laser RCW",
		["desc"] = "A protoype laser rifle design to recycle part of it's own energy.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserpdw.mdl",
		["class"] = "weapon_laser_rcw",
		["ammo"] = "ElectronChargePack",
		["type"] = "energy",
		["intelligence"] = 17,
	},

	["weapon_gatlinglaser"] = {
		["name"] = "Gatling Laser",
		["desc"] = "A large bulky Gatling Laser weapon.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/gatlinglaser.mdl",
		["class"] = "weapon_gatlaser",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},

	["weapon_plasmagatling_ke"] = {
		["name"] = "Plasma Gatling",
		["desc"] = "A large bulky Plasma Gatling.",
		["model"] = "models/independence/gatlingplasma/gatlingplasma.mdl",
		["class"] = "weapon_plasmagatling_ke",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},

	["weapon_guassminigun_le"] = {
		["name"] = "Gauss Gatling",
		["desc"] = "A large bulky Gauss Gatling.",
		["model"] = "models/independence/gaussminigun/gaussminigun.mdl",
		["class"] = "weapon_guassminigun_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},

	["weapon_tesla_ke"] = {
		["name"] = "Tesla Cannon",
		["desc"] = "A pre-wear cannon capable of mass destruction.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/teslacannon.mdl",
		["class"] = "weapon_tesla_ke",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 25,
	},

	["weapon_laserpistol"] = {
		["name"] = "Laser Pistol",
		["desc"] = "A pre-war laser pistol, a trusty sidearm.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserpistol.mdl",
		["class"] = "weapon_laserpistol_le",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 10,
	},
["gaussrifle"] = {
		["name"] = "Gauss Rifle",
		["desc"] = "A powerful energy sniper.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifle.mdl",
		["class"] = "weapon_gauss",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["enclavegaussrifle"] = {
			["name"] = "Enclave Gauss Rifle",
			["desc"] = "A powerful energy sniper developed by The Enclave.",
			["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifle.mdl",
			["class"] = "weapon_enclavegauss",
			["ammo"] = "MicrofusionCell",
			["type"] = "energy",
		},
	["gaussrifleu"] = {
		["name"] = "YCS/186 Gauss Rifle �",
		["desc"] = "A legendary energy based sniper rifle prototype.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifleunique.mdl",
		["class"] = "gaussrifleu",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
["incinerator"] = {
		["name"] = "Incinerator",
		["desc"] = "A high powered flame-induced death.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/heavyincenerator.mdl",
		["class"] = "weapon_incinerator_len",
		["ammo"] = "none",
		["type"] = "energy",
	},
	["weapon_laserrifleu"] = {
		["name"] = "AER14 Prototype Laser Rifle �",
		["desc"] = "A unique expermental laser rifle.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/laserrifleunique.mdl",
		["class"] = "weapon_laserrifleu",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_laer"] = {
		["name"] = "LAER",
		["desc"] = "A unique expermental laser rifle.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/rechargerrifle.mdl",
		["class"] = "weapon_laer_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_laserriflebs"] = {
		["name"] = "Laser Beam Splitter Rifle",
		["desc"] = "A modified laser rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_laserriflebs",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 13,
	},
	["weapon_laserpistolu"] = {
		["name"] = "Shit Shit �",
		["desc"] = "The literal worst weapon in the entire wasteland.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/laserpistolunique.mdl",
		["class"] = "weapon_laserpistol",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 30,
	},
		["weapon_enclave_laserrifle"] = {
		["name"] = "Enclave Laser Rifle",
		["desc"] = "An upgraded Laser Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_enclave_laserrifle",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
		["weapon_enclave_gatlinglaser"] = {
		["name"] = "Enclave Gatling Laser",
		["desc"] = "An upgraded Gatling Laser weapon manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/gatlinglaser.mdl",
		["class"] = "weapon_enclave_gat",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},
		["weapon_lasermusket"] = {
		["name"] = "Laser Musket",
		["desc"] = "A laser musket developed by the Minutemen.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_lasermusket",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
			["weapon_lasersniperrifle"] = {
		["name"] = "Laser Sniper Rifle",
		["desc"] = "A laser sniper rifle created and used by Think Tank.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_lasersniperrifle",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
		["weapon_teslarcw"] = {
		["name"] = "Tesla RCW",
		["desc"] = "A protoype laser rifle design to recycle part of it's own energy.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserpdw.mdl",
		["class"] = "weapon_corder_teslarcw",
		["ammo"] = "ElectronChargePack",
		["type"] = "energy",
		["intelligence"] = 17,
	},
	["weapon_mesmetron_slave"] = {
		["name"] = "Slavers Mesmetron",
		["desc"] = "A custom made Mesmetron designed to enslave it's victims.",
		["model"] = "models/halokiller38/fallout/weapons/explosives/c4det.mdl",
		["class"] = "weapon_mesmetron_slave",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 15,
	},
	["weapon_plasmarifle"] = {
		["name"] = "Plasma Rifle",
		["desc"] = "A Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 20,
	},

	["weapon_multiplasrifle"] = {
		["name"] = "Multi Plasma Rifle",
		["desc"] = "A Multi Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_multiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},

	["weapon_plasmapistol"] = {
		["name"] = "Plasma Pistol",
		["desc"] = "A Plasma Pistol.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmapistol.mdl",
		["class"] = "weapon_plasmapistol",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 15,
	},

	["weapon_plasmadefender"] = {
		["name"] = "Plasma Defender",
		["desc"] = "A Plasma Defender.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmadefender.mdl",
		["class"] = "weapon_plasmadefender",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 20,
	},
		["weapon_plasmacaster"] = {
		["name"] = "Plasma Caster",
		["desc"] = "A Plasma Caster.",
		["model"] = "models/halokiller38/fallout/weapons/plasma weapons/plasmacaster.mdl",
		["class"] = "weapon_plasmacaster_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["intelligence"] = 20,
		["powerArmor"] = true,
	},
		["weapon_enclave_plasmarifle"] = {
		["name"] = "Enclave Plasma Rifle",
		["desc"] = "An upgraded Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_enclave_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 20,
	},
		["weapon_enclave_multiplasrifle"] = {
		["name"] = "Enclave Multi Plasma Rifle",
		["desc"] = "An upgraded Multi Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_enclavemultiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},
		["fonv_pn_plrepeater"] = {
		["name"] = "Plasma Repeater",
		["desc"] = "A Plasma Repeater.",
		["model"] = "models/weapons/w_plasmarepeater.mdl",
		["class"] = "fonv_pn_plrepeater",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},
	["fonv_pn_pldisrupter"] = {
		["name"] = "Plasma Disruptor",
		["desc"] = "A Plasma Disruptor.",
		["model"] = "models/weapons/w_plasmadisrupter.mdl",
		["class"] = "fonv_pn_pldisrupter",
		["ammo"] = "MicrofusionCell",
		["type"] = "sidearm",
		["intelligence"] = 20,
	},
	["weapon_heavyplasmarepeater"] = {
		["name"] = "Heavy Plasma Repeater",
		["desc"] = "A Heavy Plasma Repeater.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_corder_heavyplasmarepeater",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},**/
}
