nut.fallout.templates.plasma = {
	["rifle"] = {
		["component_steel"] = 3,
		["component_ceramic"] = 2,
		["component_springs"] = 2,
		["component_screws"] = 3,
		["component_adhesive"] = 1,
		["component_rubber"] = 1,
		["component_nuclear_material"] = 2,
	},

	["sidearm"] = {
		["component_steel"] = 1,
		["component_ceramic"] = 1,
		["component_springs"] = 2,
		["component_screws"] = 2,
		["component_adhesive"] = 1,
		["component_rubber"] = 1,
		["component_nuclear_material"] = 1,
	},
}

nut.fallout.registry.plasma = { -- DISABLED BY KEITH / COMBINING PLASMA & LASER REGISTRY
	/** ["weapon_plasmarifle"] = {
		["name"] = "Plasma Rifle",
		["desc"] = "A Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 20,
	},

	["weapon_multiplasrifle"] = {
		["name"] = "Multi Plasma Rifle",
		["desc"] = "A Multi Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_multiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 25,
	},

	["weapon_plasmapistol"] = {
		["name"] = "Plasma Pistol",
		["desc"] = "A Plasma Pistol.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmapistol.mdl",
		["class"] = "weapon_plasmapistol",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 15,
	},

	["weapon_plasmadefender"] = {
		["name"] = "Plasma Defender",
		["desc"] = "A Plasma Defender.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmadefender.mdl",
		["class"] = "weapon_plasmadefender",
		["ammo"] = "EnergyCell",
		["type"] = "sidearm",
		["intelligence"] = 20,
	},
		["weapon_plasmacaster"] = {
		["name"] = "Plasma Caster",
		["desc"] = "A Plasma Caster.",
		["model"] = "models/halokiller38/fallout/weapons/plasma weapons/plasmacaster.mdl",
		["class"] = "weapon_plasmacaster_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["intelligence"] = 20,
		["powerArmor"] = true,
	},
		["weapon_enclave_plasmarifle"] = {
		["name"] = "Enclave Plasma Rifle",
		["desc"] = "An upgraded Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_enclave_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 20,
	},
		["weapon_enclave_multiplasrifle"] = {
		["name"] = "Enclave Multi Plasma Rifle",
		["desc"] = "An upgraded Multi Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_enclavemultiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 25,
	},
		["fonv_pn_plrepeater"] = {
		["name"] = "Plasma Repeater",
		["desc"] = "A Plasma Repeater.",
		["model"] = "models/weapons/w_plasmarepeater.mdl",
		["class"] = "fonv_pn_plrepeater",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 25,
	},
	["fonv_pn_pldisrupter"] = {
		["name"] = "Plasma Disruptor",
		["desc"] = "A Plasma Disruptor.",
		["model"] = "models/weapons/w_plasmadisrupter.mdl",
		["class"] = "fonv_pn_pldisrupter",
		["ammo"] = "MicrofusionCell",
		["type"] = "sidearm",
		["intelligence"] = 20,
	},
	["weapon_heavyplasmarepeater"] = {
		["name"] = "Heavy Plasma Repeater",
		["desc"] = "A Heavy Plasma Repeater.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_corder_heavyplasmarepeater",
		["ammo"] = "MicrofusionCell",
		["type"] = "rifle",
		["intelligence"] = 25,
	}, 	**/
}
