nut.fallout.templates.primary = {
	["rifle"] = {["component_steel"] = 3, ["component_wood"] = 2, ["component_springs"] = 2, ["component_screws"] = 3, ["component_adhesive"] = 1, ["component_rubber"] = 1},
	["sniper"] = {["component_steel"] = 4, ["component_wood"] = 2, ["component_springs"] = 2, ["component_screws"] = 5, ["component_adhesive"] = 1, ["component_rubber"] = 1},
	["shotgun"] = {["component_steel"] = 3, ["component_wood"] = 2, ["component_springs"] = 3, ["component_screws"] = 3, ["component_adhesive"] = 1, ["component_rubber"] = 1},
	["smg"] = {["component_steel"] = 2, ["component_wood"] = 1, ["component_springs"] = 2, ["component_screws"] = 4, ["component_adhesive"] = 1, ["component_rubber"] = 1},
	["heavy"] = {["component_steel"] = 6, ["component_springs"] = 4, ["component_screws"] = 4, ["component_adhesive"] = 3, ["component_rubber"] = 1},
	["energy"] = {["component_steel"] = 3, ["component_plastic"] = 2, ["component_springs"] = 2, ["component_screws"] = 3, ["component_adhesive"] = 1, ["component_rubber"] = 1, ["component_fiberoptics"] = 2}
}

nut.fallout.registry.primary = {
	["weapon_grenaderifle"] = {
		["name"] = "25mm Grenade Rifle",
		["desc"] = "A 25mm Grenade Rifle.",
		["model"] = "models/halokiller38/fallout/weapons/explosives/grenaderifle.mdl",
		["class"] = "weapon_grenaderifle_len",
		["ammo"] = "25mmGrenade",
		["type"] = "rifle",
	},
	["weapon_greatbeargrenaderifle"] = {
		["name"] = "Great Bear Grenade Rifle",
		["desc"] = "A Great Bear Grenade Rifle.",
		["model"] = "models/halokiller38/fallout/weapons/explosives/greatbeargrenaderifle.mdl",
		["class"] = "weapon_greatbeargrenaderifle_len",
		["ammo"] = "40mmGrenade",
		["type"] = "rifle",
	},
	["weapon_serviceriflereflex"] = {
		["name"] = "Service Rifle (w/ Reflex Sight)",
		["desc"] = "A Service Rifle (w/ Reflex Sight).",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/battlerifleap.mdl",
		["class"] = "weapon_servicerifle_wscope",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_bozar_len"] = {
		["name"] = "Bozar",
		["desc"] = "A hand-crafted Assault Rifle.",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/infiltrator.mdl",
		["class"] = "weapon_bozar_len",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_fortification_hammer"] = {
		["name"] = "Fortifications Hammer",
		["desc"] = "A hand-crafted specialized hammer that allows the usage of fortification creation.",
		["model"] = "models/clutter/hammer.mdl",
		["class"] = "hammer",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_sniperriflesil"] = {
		["name"] = "Supressed Sniper Rifle",
		["desc"] = "A Supressed Sniper Rifle that is quieter and conceals it's tracer | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/Halokiller38/fallout/weapons/SniperRifles/sniperriflesupressor.mdl",
		["class"] = "weapon_supressed_sniper_len",
		["ammo"] = "308",
		["type"] = "sniper",
	},
	["weapon_huntingriflescp"] = {
		["name"] = "Hunting Rifle (w/ Scope)",
		["desc"] = "A Hunting Rifle (w/ Scope).",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/huntingriflescoped.mdl",
		["class"] = "weapon_huntingrifle_len",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_brushgun_len"] = {
		["name"] = "Brush Gun",
		["desc"] = "A high calibur rifle used often by the Heroic Type.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/brushgun.mdl",
		["class"] = "weapon_brushgun_len",
		["ammo"] = "70Govt",
		["type"] = "rifle",
	},
	["weapon_huntingrifle_ke"] = {
		["name"] = "Hunting Rifle",
		["desc"] = "A Scopeless Hunting Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/huntingriflescoped.mdl",
		["class"] = "weapon_huntingrifle_ke",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_huntingrifle_mole"] = {
		["name"] = "Mole Miner Hunting Rifle",
		["desc"] = "A Scopeless Hunting Rifle salvaged and used by Molemen.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/huntingriflescoped.mdl",
		["class"] = "weapon_huntingrifle_mole",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_thumpthump"] = {
		["name"] = "Thump-Thump",
		["desc"] = "A Thump-Thump.",
		["model"] = "models/halokiller38/fallout/weapons/explosives/grenaderifleunique.mdl",
		["class"] = "weapon_thumpthump",
		["ammo"] = "40mmGrenade",
		["type"] = "rifle",
	},
	["weapon_antimaterielrifle1"] = {
		["name"] = "Anti-Material Rifle",
		["desc"] = "A powerful Sniper Rifle manufactured by weapon smiths in the West | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/Halokiller38/fallout/weapons/SniperRifles/antimaterielrifle.mdl",
		["class"] = "weapon_antimat",
		["ammo"] = "50MG",
		["type"] = "sniper",
		["intelligence"] = 15,
	},
	["weapon_antimaterielrifle_ncr"] = {
		["name"] = "NCR Anti-Material Rifle",
		["desc"] = "A powerful Sniper Rifle manufactured by skilled weapon smiths in the New California Republic | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/Halokiller38/fallout/weapons/SniperRifles/antimaterielrifle.mdl",
		["class"] = "weapon_antimat_ncr",
		["ammo"] = "50MG",
		["type"] = "sniper",
		["intelligence"] = 15,
		["brand"] = "New California Republic"
	},
	["weapon_antimaterielrifle_legion"] = {
		["name"] = "Legion Anti-Material Rifle",
		["desc"] = "A powerful Sniper Rifle scavenged from fallen Rangers | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/Halokiller38/fallout/weapons/SniperRifles/antimaterielrifle.mdl",
		["class"] = "weapon_legion_antimat",
		["ammo"] = "50MG",
		["type"] = "sniper",
		["intelligence"] = 15,
		["brand"] = "Caesar's Legion"
	},
	["weapon_r91assaultrifle"] = {
		["name"] = "R91 Assault Rifle",
		["desc"] = "R91 Assault Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/r91assaultrifle.mdl",
		["class"] = "weapon_r91_carb",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_combatshotgun"] = {
		["name"] = "Combat Shotgun",
		["desc"] = "A Combat Shotgun.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/r91assaultrifle.mdl",
		["class"] = "weapon_combatshot",
		["ammo"] = "20Gauge",
		["type"] = "shotgun",
	},
	["weapon_railwayrifle"] = {
		["name"] = "Railway Rifle",
		["desc"] = "A Railway Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/railwayrifle.mdl",
		["class"] = "weapon_railway_len",
		["ammo"] = "RailwaySpike",
		["type"] = "rifle",
	},
	["weapon_minigun"] = {
		["name"] = "Minigun",
		["desc"] = "A Minigun.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigun.mdl",
		["class"] = "weapon_minigun_len",
		["ammo"] = "5mm",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_riotshotgun"] = {
		["name"] = "Riot Shotgun",
		["desc"] = "A Riot Pin. A magical weapon that smells of 12 Gauge spam.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/riotshotgun.mdl",
		["class"] = "weapon_riotshot",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_varmintriflesilext"] = {
		["name"] = "Varmint Rifle",
		["desc"] = "A Varmint Rifle with an extended clip and a supressor.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/varmintriflesilext.mdl",
		["class"] = "weapon_varmintrifle_len",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_battlerifle"] = {
		["name"] = "Battle Rifle",
		["desc"] = "A Battle Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/thismachine.mdl",
		["class"] = "weapon_battlerifle_len",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_chineseassaultrifle"] = {
		["name"] = "Chinese Assault Rifle",
		["desc"] = "A Chinese Assault Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/chineseassaultrifle.mdl",
		["class"] = "weapon_chinese_ar",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_chinese_ar_mole"] = {
		["name"] = "Mole Miner Chinese Assault Rifle",
		["desc"] = "A Chinese Assault Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/chineseassaultrifle.mdl",
		["class"] = "weapon_chinese_ar_mole",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_huntingshotgun"] = {
		["name"] = "Hunting Shotgun",
		["desc"] = "A Hunting Shotgun.",
		["model"] = "models/Halokiller38/fallout/weapons/Shotguns/huntingshotgun.mdl",
		["class"] = "weapon_huntingshotgun_len",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_assaultcarbinesil"] = {
		["name"] = "Silenced Assault Carbine",
		["desc"] = "A Silenced Assault Carbine.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/assaultcarbinesilencer.mdl",
		["class"] = "weapon_assaultcarbinesil",
		["ammo"] = "5mm",
		["type"] = "rifle",
	},
	["weapon_huntingrifleext"] = {
		["name"] = "Hunting Rifle (Extended Clip)",
		["desc"] = "A Extended Clip Hunting Rifle that has 8 rounds compared to the normal 5 of a Hunting rifle",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/huntingrifleext.mdl",
		["class"] = "weapon_huntingrifle_ke_extended",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_cowboyrepeater"] = {
		["name"] = "Cowboy Repeater",
		["desc"] = "A old fashion Cowboy Repeater.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/cowboyrepeater.mdl",
		["class"] = "weapon_cowboyrepeater_len",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["weapon_cowboyrepeater_legion"] = {
		["name"] = "Salvaged Cowboy Repeater",
		["desc"] = "A rusty Cowboy Repeater, scavenged from the battlefields of Caesar's Legion.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/cowboyrepeater.mdl",
		["class"] = "weapon_core_cowboyrep",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["weapon_cowboyrepeater_ncr"] = {
		["name"] = "Refined Cowboy Repeater",
		["desc"] = "A refined Cowboy Repeater, crafted for the battlefields of The New California Republic.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/cowboyrepeater.mdl",
		["class"] = "weapon_core_cowboyrep",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["weapon_leveractionrifle"] = {
		["name"] = "Lever Action Shotgun",
		["desc"] = "A lever action Shotgun.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/leveractionrifle.mdl",
		["class"] = "weapon_leveraction",
		["ammo"] = "12Gauge",
		["type"] = "rifle",
	},
	["weapon_bar"] = {
		["name"] = "Automatic Rifle",
		["desc"] = "A pre-war BAR.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/automaticrifle.mdl",
		["class"] = "weapon_automaticbar_len",
		["ammo"] = "5mm",
		["type"] = "rifle",
	},
/**	-- Moved to secondary registry
	["weapon_sawedoffshotgweapon_trailcarbine_len un"] = {
		["name"] = "Sawed Off Shotgun",
		["desc"] = "A 'Mad Max' of a weapon.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/sawedoffshotgun.mdl",
		["class"] = "weapon_sawnoffshot_len",
		["ammo"] = "shotgunr",
		["type"] = "shotgun",
	},
**/

	["weapon_trailcarbine"] = {
		["name"] = "Trail Carbine",
		["desc"] = "A lethal carbine of the wasteland | Takes .44 Magnum Rounds",
		["model"] = "models/halokiller38/fallout/weapons/rifles/trailcarbine.mdl",
		["class"] = "weapon_trailcarbine_len",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["flamethrower"] = {
		["name"] = "Flamethrower",
		["desc"] = "BURN, BABY, BURN.",
		["model"] = "models/weapons/w_flamer.mdl",
		["class"] = "weapon_flamer_reworked",
		["ammo"] = "none",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_yaoguaigauntlet"] = {
		["name"] = "Yao Guai Guantlet �",
		["desc"] = "RAWR",
		["model"] = "models/halokiller38/fallout/weapons/melee/yaoguiguantlet.mdl",
		["class"] = "weapon_yaoguaigauntlet",
		["ammo"] = "Fury",
		["type"] = "Fister",
	},
	["weapon_marksmancarbine"] = {
		["name"] = "Marksman Carbine",
		["desc"] = "A marksman carbine",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbine.mdl",
		["class"] = "weapon_marksmancarbine",
		["ammo"] = "5mm",
		["type"] = "rifle",
	},
	["weapon_corder_xm8"] = {
		["name"] = "XM8 Assault Rifle",
		["desc"] = "A lightweight assault rifle used by Univeral Energy",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbine.mdl",
		["class"] = "weapon_corder_xm8",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_marksmancarbine_legion"] = {
		["name"] = "Salvaged Marksman Carbine",
		["desc"] = "A salvaged marksman carbine, grabbed from the battlefields of the Caesar's Legion",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbine.mdl",
		["class"] = "weapon_core_markrifle",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_marksmancarbine_ncr"] = {
		["name"] = "Refined Marksman Carbine",
		["desc"] = "A refined marksman carbine, crafted for the battlefields of the New California Republic",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbine.mdl",
		["class"] = "weapon_core_markrifle",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_marksmancarbinea"] = {
		["name"] = "All American",
		["desc"] = "A marksman carbine",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbinea.mdl",
		["class"] = "weapon_aa_len",
		["ammo"] = "5.56mm",
		["type"] = "rifle",
	},
	["weapon_lmgext"] = {
		["name"] = "Light Machine Gun",
		["desc"] = "A light machine gun",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/lightmachinegunext.mdl",
		["class"] = "weapon_lightmachine_gun",
		["ammo"] = "5.56mm",
		["type"] = "rifle",
	},
	["weapon_minigun_mole"] = {
		["name"] = "Mole Miner Minigun",
		["desc"] = "A minigun salvaged and refurbished by the Mole Miners.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigunallmods.mdl",
		["class"] = "weapon_moddedminigun_len",
		["ammo"] = "5mm",
		["type"] = "heavy",
	},
	["weapon_minigunallmods"] = {
		["name"] = "Modified Minigun",
		["desc"] = "A modified minigun.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigunallmods.mdl",
		["class"] = "weapon_moddedminigun_len",
		["ammo"] = "5mm",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_minigunu"] = {
		["name"] = "CZ57 Avenger",
		["desc"] = "A unique minigun.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigununique.mdl",
		["class"] = "weapon_avenger_len",
		["ammo"] = "5mm",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_riotshotgunn"] = {
		["name"] = "Tell Admin / Code: RS",
		["desc"] = "A Riot Shotgun",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/lightmachinegunext.mdl",
		["class"] = "weapon_riotshotgun",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_singleshotgun"] = {
		["name"] = "Single Shotgun",
		["desc"] = "A Single Shotgun",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/caravanshotgun.mdl",
		["class"] = "weapon_singleshotgun",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_serviceriflebayo"] = {
		["name"] = "Service Rifle",
		["desc"] = "A Service Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/battlerifleap.mdl",
		["class"] = "weapon_service_rifle",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_service_rifle_mkii"] = {
		["name"] = "Service Rifle MKII",
		["desc"] = "A burst-fire upgraded Service Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/AssaultRifles/battlerifleap.mdl",
		["class"] = "weapon_service_rifle_mkii",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_smmg"] = {
		["name"] = "Shoulder-mounted Machine Gun",
		["desc"] = "A powerful shoulder-mounted machine gun.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/shouldermountedmg.mdl",
		["class"] = "weapon_smmg_len",
		["ammo"] = "10mm",
		["type"] = "heavy",
	},
	["weapon_riotshotgun"] = {
		["name"] = "Riot Shotgun",
		["desc"] = "The most disguisting weapon in the wasteland.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/riotshotgun.mdl",
		["class"] = "weapon_riotshot",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_sniperrifleu"] = {
		["name"] = "Gobi Campaign Sniper Rifle",
		["desc"] = "A campaign of blood, swet, and probably more blood | This weapon uses larger bullets and is much more likely to hit a target | UNIQUE LEGENDARY",
		["model"] = "models/halokiller38/fallout/weapons/sniperrifles/sniperrifleunique.mdl",
		["class"] = "weapon_gobicampaign_len",
		["ammo"] = "308",
		["type"] = "Sniper",
	},
	["weapon_alienblaster_len"] = {
		["name"] = "Alien Blaster",
		["desc"] = "Can the english language even describe an Alien Blaster? | UNIQUE LEGENDARY",
		["model"] = "models/fallout/weapons/w_alienblaster.mdl",
		["class"] = "weapon_alienblaster_len",
		["ammo"] = "Alien",
		["type"] = "energy",
	},
	["weapon_25mmgrndlnchr"] = {
		["name"] = "Mercy",
		["desc"] = "If only I had any to give. | UNIQUE LEGENDARY",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/25mmgrndlnchr.mdl",
		["class"] = "weapon_mercy_len",
		["ammo"] = "25mm",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_caravanshotgun"] = {
		["name"] = "Caravan Shotgun",
		["desc"] = "A caravan shotgun.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/caravanshotgun.mdl",
		["class"] = "weapon_bosg_len",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_bosg_mole"] = {
		["name"] = "Mole Miner Shotgun",
		["desc"] = "A reconstructed Caravan Shotgun. Now used by the Mole Miners.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/caravanshotgun.mdl",
		["class"] = "weapon_bosg_mole",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_huntingshotextchoke"] = {
		["name"] = "Double Barrel Shotgun",
		["desc"] = "The iconinc close-quarters-glass-cannon.",
		["model"] = "models/fo3_double_shotty.mdl",
		["class"] = "weapon_corder_db",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_huntingshotgunu"] = {
		["name"] = "Dinner Bell",
		["desc"] = "A legendary shotgun.",
		["model"] = "models/halokiller38/fallout/weapons/shotguns/huntingshotgununique.mdl",
		["class"] = "weapon_huntingshotgunu",
		["ammo"] = "12Gauge",
		["type"] = "shotgun",
	},
	["weapon_sniperrifle"] = {
		["name"] = "Sniper Rifle",
		["desc"] = "A powerful long-range sniper rifle  | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/halokiller38/fallout/weapons/sniperrifles/sniperrifle.mdl",
		["class"] = "weapon_sniper_len",
		["ammo"] = "308",
		["type"] = "Sniper",
	},
	["weapon_sniperriflecf"] = {
		["name"] = "Modded Sniper Rifle",
		["desc"] = "A powerful modified sniper rifle that deals more damange in exchange for accuracy and recoil  | This weapon uses larger bullets and is much more likely to hit a target.",
		["model"] = "models/halokiller38/fallout/weapons/sniperrifles/sniperrifle.mdl",
		["class"] = "weapon_modded_sniper_len",
		["ammo"] = "308",
		["type"] = "Sniper",
	},
	["weapon_ratslayerr"] = {
		["name"] = "Ratslayer �",
		["desc"] = "A sniper typically used to kill Giant rats  | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/halokiller38/fallout/weapons/sniperrifles/ratslayer.mdl",
		["class"] = "weapon_ratslayer",
		["ammo"] = "308",
		["type"] = "Sniper",
	},
	["weapon_cowboyrepeaterbrass"] = {
		["name"] = "Brass Cowboy Repeater",
		["desc"] = "A brass Cowboy Repeater.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/cowboyrepeaterbrass.mdl",
		["class"] = "weapon_brasscowboyrepeater_len",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["weapon_cowboyrepeateru"] = {
		["name"] = "La Longue Carabine",
		["desc"] = "A legendary Cowboy Repeater.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/cowboyrepeaterunique.mdl",
		["class"] = "weapon_cowboyrepeateru",
		["ammo"] = "357Magnum",
		["type"] = "rifle",
	},
	["weapon_assaultcarbine"] = {
		["name"] = "Assault Carbine",
		["desc"] = "An assault carbine",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/assaultcarbine.mdl",
		["class"] = "weapon_assault_carbine_l",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
		["moons_fatman"] = {
		["name"] = "Fatman",
		["desc"] = "A highly explosive Fatman rocket launcher.",
		["model"] = "models/fallout/weapons/w_fatman.mdl",
		["class"] = "weapon_fatman_len",
		["ammo"] = "mininuke",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
		["weapon_missilelauncher"] = {
		["name"] = "Missile Launcher",
		["desc"] = "A highly explosive missile launcher.",
		["model"] = "models/halokiller38/fallout/weapons/rocketlaunchers/missilelauncher.mdl",
		["class"] = "weapon_missilelauncher_len",
		["ammo"] = "Rocket",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
		["weapon_bbgun"] = {
		["name"] = "Paintball Gun",
		["desc"] = "A paintball gun that deals nearly no damage. A great weapon for combat training and scaring off pests.",
		["model"] = "models/halokiller38/fallout/weapons/sniperrifles/ratslayer.mdl",
		["class"] = "weapon_bbgun_ke",
		["ammo"] = "none",
		["type"] = "rifle",
	},
		["weapon_bmissilelauncher"] = {
		["name"] = "Boomers Missile Launcher MKII",
		["desc"] = "A highly explosive missile launcher that does not require Power Armor to wield.",
		["model"] = "models/halokiller38/fallout/weapons/rocketlaunchers/missilelauncher.mdl",
		["class"] = "weapon_missilelauncher_len",
		["ammo"] = "Rocket",
		["type"] = "heavy",
		["powerArmor"] = false,
		["brand"] = "Boomers"
	},
		["weapon_25mmgrndlnchrb"] = {
		["name"] = "Boomers Grenade Machinegun Rifle MKII",
		["desc"] = "A Grenade machine gun launcher.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/25mmgrndlnchr.mdl",
		["class"] = "weapon_gmg_len",
		["ammo"] = "25mm",
		["type"] = "heavy",
		["powerArmor"] = false,
		["brand"] = "Boomers"
	},
		["weapon_longbarrelgrenaderifle"] = {
		["name"] = "Boomers 25mm Grenade Rifle MKII",
		["desc"] = "A 25mm Grenade Rifle",
		["model"] = "models/halokiller38/fallout/weapons/explosives/grenaderifle.mdl",
		["class"] = "weapon_longbarrelgrenaderifle_len",
		["ammo"] = "25mmGrenade",
		["type"] = "rifle",
		["brand"] = "Boomers"
	},
	["weapon_teslacannon"] = {
		["name"] = "Tesla Cannon",
		["desc"] = "A highly powerful tesla cannon.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/teslacannon.mdl",
		["class"] = "weapon_teslacannon",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_defib"] = {
		["name"] = "Defibrillator",
		["desc"] = "Highly electrified shock pads that can be used to revive injured people. It must be charged and applied for at least 3 seconds.",
		["model"] = "models/weapons/w_medkit.mdl",
		["class"] = "weapon_defib",
		["ammo"] = "None",
		["type"] = "smg",
	},
	["weapon_redglare"] = {
		["name"] = "Red Glare",
		["desc"] = "God himself shall know the wrath of the American Dream | UNIQUE LEGENDARY",
		["model"] = "models/props_fallout/redglare.mdl",
		["class"] = "weapon_redglare_len",
		["ammo"] = "Rocket",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_gyrojetlmg"] = { -- Custom Weapon order content
		["name"] = "Gyro Jet HMG",
		["desc"] = "A make-shit heavy machienegun",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/lightmachinegunext.mdl",
		["class"] = "weapon_gyrojetlmg-",
		["ammo"] = "5mm",
		["type"] = "rifle",
	},
	["weapon_crossbow"] = {
		["name"] = "Crossbow",
		["desc"] = "A make-shift crossbow",
		["model"] = "models/weapons/w_crossbow.mdl",
		["class"] = "medieval_crossbow",
		["ammo"] = "none",
		["type"] = "rifle",
	},
	["cleansing_flamethrower"] = { -- Custom Weapon order content
		["name"] = "Cleansing Flame",
		["desc"] = "A flamethrower that burns even Hell itself",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/flamer.mdl",
		["class"] = "weapon_corder_cflamer",
		["ammo"] = "none",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_acr"] = {
		["name"] = "ACR",
		["desc"] = "A pre-war military machine-gun",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbinea.mdl",
		["class"] = "weapon_corder_acr",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_tommygun"] = {
		["name"] = "Tommy Gun",
		["desc"] = "The Mobster's weapon of choice",
		["model"] = "models/halokiller38/fallout/weapons/smgs/45smg.mdl",
		["class"] = "weapon_corder_tommygun",
		["ammo"] = "5mm",
		["type"] = "rifle",
	},
	["weapon_mesmetron"] = { -- Custom Weapon order content
		["name"] = "Mesmetron",
		["desc"] = "A mind-control device | This weapon has a weapon rule: Advanced Rules Page",
		["model"] = "models/halokiller38/fallout/weapons/explosives/c4det.mdl",
		["class"] = "weapon_mesmetron_fixed",
		["ammo"] = "energycell",
		["type"] = "rifle",
	},
	["weapon_thepatriot"] = { -- Custom Weapon order content
		["name"] = "The Patriot",
		["desc"] = "An old automatic rifle used by Pre-War paratroopers",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbinea.mdl",
		["class"] = "weapon_corder_thepatriot",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["fas2_ifak"] = {
		["name"] = "Military Medical Kit",
		["desc"] = "A medical kit used to heal injuries.",
		["model"] = "models/weapons/w_medkit.mdl",
		["class"] = "hotmedkit",
		["ammo"] = "none",
		["type"] = "pistol",
	},
	["weapon_mrgatling"] = { -- Custom Weapon order content
		["name"] = "Mr. Gatling",
		["desc"] = "A heavily customized gatling gun.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigunallmods.mdl",
		["class"] = "weapon_corder_mrgatling",
		["ammo"] = "5mm",
		["type"] = "heavy",
		["powerArmor"] = true,
	},
	["weapon_m9"] = {
		["name"] = "Tranquillizer [DISABLED]",
		["desc"] = "This Weapons has been disabled by the Development Team",
		["model"] = "models/halokiller38/fallout/weapons/pistols/10mmpistolsilenced.mdl",
		["class"] = "",
		["ammo"] = "none",
		["type"] = "pistol",
	},
	["weapon_syringer"] = { -- Custom Weapon order content
		["name"] = "Syringer",
		["desc"] = "A Syringer Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/railwayrifle.mdl",
		["class"] = "weapon_corder_syringer",
		["ammo"] = "RailwaySpike",
		["type"] = "rifle",
	},
	["weapon_sa80"] = { -- Custom Weapon order content
		["name"] = "SA80 Assault Rifle",
		["desc"] = "An assault Rifle that yields high damage but poor accuracy.",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbine.mdl",
		["class"] = "weapon_corder_sa80",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_cryolator_len"] = { -- Custom Weapon order content
		["name"] = "Cryolator",
		["desc"] = "A freezing explosive weapon.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/railwayrifle.mdl",
		["class"] = "weapon_corder_cryolator",
		["ammo"] = "ElectronChargePack",
		["type"] = "rifle",
	},
	["weapon_revosniper"] = { -- Custom Weapon order content
		["name"] = "Revo Sniper",
		["desc"] = "A highly modified revolver that has been rigged into a Sniper. Used and created by The Nomads.",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/huntingrifleext.mdl",
		["class"] = "weapon_corder_revosniper",
		["ammo"] = ".44",
		["type"] = "sniper",
	},
	["weapon_laserriflescp"] = {
		["name"] = "Scoped Laser Rifle",
		["desc"] = "A laser rifle with an attached scope.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserriflescope.mdl",
		["class"] = "weapon_laserrifle_scoped_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
	["weapon_tribeam"] = {
		["name"] = "Tribeam Laser Rifle",
		["desc"] = "A pre-war laser rifle fitted with a tri-beam splitter.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/tribeamlaserrifle.mdl",
		["class"] = "weapon_laser_tribeam",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 15,
	},
	["weapon_laserrifle"] = {
		["name"] = "Laser Rifle",
		["desc"] = "A standard, common issue pre-war laser rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_laserrifle_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
	["weapon_laserpdw"] = {
		["name"] = "Recyling Laser RCW",
		["desc"] = "A protoype laser rifle design to recycle part of it's own energy.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserpdw.mdl",
		["class"] = "weapon_laser_rcw",
		["ammo"] = "ElectronChargePack",
		["type"] = "energy",
		["intelligence"] = 17,
	},
	["weapon_gatlinglaser"] = {
		["name"] = "Gatling Laser",
		["desc"] = "A large bulky Gatling Laser weapon.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/gatlinglaser.mdl",
		["class"] = "weapon_gatlaser",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},
	["weapon_gatlinglaser_bos"] = {
		["name"] = "BOS Gatling Laser",
		["desc"] = "An upgraded Gatling Laser weapon manufactured by Brotherhood of Steel",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/gatlinglaser.mdl",
		["class"] = "weapon_gatlaser_bos",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
		["brand"] = "Brotherhood of Steel"
	},
	["weapon_plasmagatling_ke"] = {
		["name"] = "Plasma Gatling",
		["desc"] = "A large bulky Plasma Gatling.",
		["model"] = "models/independence/gatlingplasma/gatlingplasma.mdl",
		["class"] = "weapon_plasmagatling",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},
	["weapon_guassminigun_le"] = {
		["name"] = "Gauss Gatling",
		["desc"] = "A large bulky Gauss Gatling.",
		["model"] = "models/independence/gaussminigun/w_gaussminigun.mdl",
		["class"] = "weapon_guassminigun_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},
	["weapon_tesla_ke"] = {
		["name"] = "Tesla Cannon",
		["desc"] = "A pre-wear cannon capable of mass destruction.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/teslacannon.mdl",
		["class"] = "weapon_tesla_ke",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 25,
	},
	["gaussrifle"] = {
		["name"] = "Gauss Rifle",
		["desc"] = "A powerful energy sniper | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifle.mdl",
		["class"] = "weapon_gauss_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["enclavegaussrifle"] = {
		["name"] = "Enclave Gauss Rifle",
		["desc"] = "A powerful energy sniper developed by The Enclave",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifle.mdl",
		["class"] = "weapon_enclavegauss",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["brand"] = "Enclave"
	},
	["gaussrifleu"] = {
		["name"] = "YCS/186 Gauss Rifle",
		["desc"] = "Y the long face? Oh shit his head's fucking gone | UNIQUE LEGENDARY",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifleunique.mdl",
		["class"] = "weapon_ycs_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_gaussmusket"] = {
		["name"] = "Gauss Musket",
		["desc"] = "A reverse engineered Gauss Rifle that unleashes a powerful long-range energy blasst that can be charged up twice for even greater output",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_gaussmusket",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_incinerator_ke"] = {
		["name"] = "Incinerator",
		["desc"] = "A high powered flame blaster used during the Great War by the United Stated Armed Forces",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/heavyincenerator.mdl",
		["class"] = "weapon_incinerator_ke",
		["ammo"] = "none",
		["type"] = "energy",
	},
	["incinerator"] = {
		["name"] = "Enclave Incinerator",
		["desc"] = "A high powered flame blaster formally known to be used and enhanced by The Enclave",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/heavyincenerator.mdl",
		["class"] = "weapon_incinerator_len",
		["ammo"] = "none",
		["type"] = "energy",
		["brand"] = "Enclave"
	},
	["weapon_laserrifleu"] = {
		["name"] = "AER14 Prototype Laser Rifle �",
		["desc"] = "A unique expermental laser rifle.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/laserrifleunique.mdl",
		["class"] = "weapon_laserrifleu",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_laer"] = {
		["name"] = "LAER",
		["desc"] = "A unique expermental laser rifle created by the Mad Scientists of the Big M.T.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/rechargerrifle.mdl",
		["class"] = "weapon_laer_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_laserriflebs"] = {
		["name"] = "Laser Beam Splitter Rifle",
		["desc"] = "A modified laser rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_laserriflebs",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 13,
	},
	["weapon_enclave_laserrifle"] = {
		["name"] = "Enclave Laser Rifle",
		["desc"] = "An upgraded Laser Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserrifle.mdl",
		["class"] = "weapon_enclavelaserrifle_le",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
		["brand"] = "Enclave"
	},
	["weapon_enclave_gatlinglaser"] = {
		["name"] = "Enclave Gatling Laser",
		["desc"] = "An upgraded Gatling Laser weapon manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/gatlinglaser.mdl",
		["class"] = "weapon_enclave_gat",
		["ammo"] = "ElectronChargePack",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
		["brand"] = "Enclave"
	},
	["weapon_lasermusket"] = {
		["name"] = "Laser Musket",
		["desc"] = "A laser musket developed by the Minutemen.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_lasermusket",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
	["weapon_lasermusketscopd"] = {
		["name"] = "Laser Musket (Scoped)",
		["desc"] = "A laser musket (Scoped) developed by the Minutemen.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_lasermusketscopd",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
	["weapon_lasersniperrifle"] = {
		["name"] = "WATZZ Laser Sniper Rifle",
		["desc"] = "A laser rifle that has been equipped with highly powerful sniper modifications  | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/weapons/customorders3/w_wattz_len.mdl",
		["class"] = "weapon_corder_wattz",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 12,
	},
	["weapon_teslarcw"] = {
		["name"] = "Tesla RCW",
		["desc"] = "A protoype laser rifle design to recycle part of it's own energy.",
		["model"] = "models/Halokiller38/fallout/weapons/Energy Weapons/laserpdw.mdl",
		["class"] = "weapon_corder_teslarcw",
		["ammo"] = "ElectronChargePack",
		["type"] = "energy",
		["intelligence"] = 17,
	},
	["weapon_mesmetron_slave"] = {
		["name"] = "Slavers Mesmetron",
		["desc"] = "A custom made Mesmetron designed to enslave it's victims.",
		["model"] = "models/halokiller38/fallout/weapons/explosives/c4det.mdl",
		["class"] = "weapon_mesmetron_slave",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 15,
	},
	["weapon_plasmarifle"] = {
		["name"] = "Plasma Rifle",
		["desc"] = "A Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 20,
	},

	["weapon_corder_protgauss"] = {
		["name"] = "Prototype Plasma Rifle",
		["desc"] = "A variant of the plasma rifle developed by the Washington Brotherhood.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_corder_protplasma",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 20,
	},

	["weapon_multiplasrifle"] = {
		["name"] = "Multi Plasma Rifle",
		["desc"] = "A Multi Plasma Rifle.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_multiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},

	["weapon_plasmacaster"] = {
		["name"] = "Plasma Caster",
		["desc"] = "A Plasma Caster.",
		["model"] = "models/halokiller38/fallout/weapons/plasma weapons/plasmacaster.mdl",
		["class"] = "weapon_plasmacaster_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["intelligence"] = 20,
		["powerArmor"] = true,
	},
	["weapon_enclave_plasmarifle"] = {
		["name"] = "Enclave Plasma Rifle",
		["desc"] = "An upgraded Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/plasmarifle.mdl",
		["class"] = "weapon_enclave_plasmarifle_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 20,
		["brand"] = "Enclave"
	},
	["weapon_enclave_multiplasrifle"] = {
		["name"] = "Enclave Multi Plasma Rifle",
		["desc"] = "An upgraded Multi Plasma Rifle manufactured by The Enclave.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_enclavemultiplas_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
		["brand"] = "Enclave"
	},
	["fonv_pn_plrepeater"] = {
		["name"] = "Plasma Repeater",
		["desc"] = "A Plasma Repeater.",
		["model"] = "models/weapons/w_plasmarepeater.mdl",
		["class"] = "weapon_plasmarepeater_len",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},
	["weapon_heavyplasmarepeater"] = { -- Custom Weapon order content
		["name"] = "Heavy Plasma Repeater",
		["desc"] = "A Heavy Plasma Repeater.",
		["model"] = "models/Halokiller38/fallout/weapons/Plasma Weapons/multiplasrifle.mdl",
		["class"] = "weapon_corder_heavyplasmarepeater",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
		["intelligence"] = 25,
	},
	["weapon_corder_cyberdog"] = { -- Custom Weapon order content
		["name"] = "K9000 Cyberdog Gun",
		["desc"] = "Bark Bark!",
		["model"] = "models/weapons/customorders3/w_cyberdoggun_len.mdl",
		["class"] = "weapon_corder_cyberdog",
		["ammo"] = "357Magnum",
		["type"] = "heavy",
		["powerArmor"] = true,
		["intelligence"] = 20,
	},
	["weapon_corder_m2browning"] = { -- Custom Weapon order content
		["name"] = "M2 Browning",
		["desc"] = "A heavy machinegun refurbished from pre-war remnants by weapon smiths in New California.",
		["model"] = "models/weapons/customorders3/w_m2browning_len.mdl",
		["class"] = "weapon_corder_m2browning",
		["ammo"] = "50MG",
		["type"] = "heavy",
		["intelligence"] = 20,
	},
	["weapon_corder_minilauncher"] = { -- Custom Weapon order content
		["name"] = "Minilauncher",
		["desc"] = "A mini-explosive launcher that was refurbished from scrapped New Vegas Securitrons",
		["model"] = "models/halokiller38/fallout/weapons/rocketlaunchers/missilelauncher.mdl",
		["class"] = "weapon_corder_minilauncher",
		["ammo"] = "Missiles",
		["type"] = "heavy",
	},
	["weapon_corder_dp28"] = { -- Custom Weapon order content
		["name"] = "DP-28 Machine Gun",
		["desc"] = "Also known as the Degtyaryov machine gun, a pre-war weapon used by the Soviet Union during the Great War that has been refurbished for wasteland warfare.",
		["model"] = "models/halokiller38/fallout/weapons/smgs/22smgext.mdl",
		["class"] = "weapon_corder_dp28",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_corder_fal"] = { -- Custom Weapon order content
		["name"] = "The Liberator",
		["desc"] = "Also known as the Fusil Automatique Leger, or the FAL for short. This weapon was used by the French during the Great War and has been refurbished to now help liberate the wasteland as well.",
		["model"] = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbineext.mdl",
		["class"] = "weapon_corder_fal",
		["ammo"] = "308",
		["type"] = "rifle",
	},
	["weapon_corder_holorifle"] = { -- Custom Weapon order content
		["name"] = "Holorifle",
		["desc"] = "Also known as the Hologram Rifle. A custom energy weapon model type created by Father Elijah, the Mad Elder, from technology obtained from the Big MT.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/holorifle.mdl",
		["class"] = "weapon_corder_holorifle",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_corder_r91"] = { -- Custom Weapon order content
		["name"] = "Raider-91",
		["desc"] = "The Raider-91, or a highly modified R91 Assault Rifle to be exact. This is a R91 assault rifle that has been modified to near unrecognizable extent by Raiders of the wasteland for even more murderous effeciency.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/lightmachinegun.mdl",
		["class"] = "weapon_corder_r91",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_corder_railwaysniper"] = { -- Custom Weapon order content
		["name"] = "Railyway Sniper",
		["desc"] = "The railway sniper is an even more jerry-rigged railway rifle that now blasts objects with even more power and range but at the cost of reload time  | This weapon uses larger bullets and is much more likely to hit a target",
		["model"] = "models/Halokiller38/fallout/weapons/Rifles/railwayrifle.mdl",
		["class"] = "weapon_corder_railwaysniper",
		["ammo"] = "RailwaySpike",
		["type"] = "sniper",
	},
	["weapon_corder_mefcaster"] = { -- Custom Weapon order content
		["name"] = "P94 Plasma Caster",
		["desc"] = "An alternative plasma caster variant that has been modified to have increased damage and accuracy but reduced fire rate.",
		["model"] = "models/weapons/customorders3/w_mefcaster_len.mdl",
		["class"] = "weapon_corder_mefcaster",
		["ammo"] = "MicrofusionCell",
		["type"] = "heavy",
		["intelligence"] = 20,
		["powerArmor"] = true,
	},
	["harpoon_hook"] = {
		["name"] = "Crosshook",
		["desc"] = "A crossbow equipped with a hook used for kidnapping",
		["model"] = "models/weapons/w_crossbow.mdl",
		["class"] = "harpoon_hook",
		["ammo"] = "none",
		["type"] = "rifle",
	},
	["tfa_fwp_combatrifle"] = {
		["name"] = "Combat Rifle",
		["desc"] = "A scrapped together rifle of higher quality than typically expected of wasteland engineers.",
		["model"] = "models/illusion/fwp/w_combatrifle.mdl",
		["class"] = "tfa_fwp_combatrifle",
		["ammo"] = "45Auto",
		["type"] = "rifle",
	},
	["tfa_fwp_piperiflesemi"] = {
		["name"] = "Pipe Rifle",
		["desc"] = "A scrapped together semi-auto rifle made of pipe.",
		["model"] = "models/illusion/fwp/w_piperiflesemi.mdl",
		["class"] = "tfa_fwp_piperiflesemi",
		["ammo"] = "railway",
		["type"] = "rifle",
	},
	["weapon_handmadear"] = {
		["name"] = "Handmade Rifle",
		["desc"] = "A scrapped together full-auto rifle made of pipe.",
		["model"] = "models/illusion/fwp/w_hmar.mdl",
		["class"] = "weapon_handmadear",
		["ammo"] = "railway",
		["type"] = "rifle",
	},
	["weapon_corder_m14"] = {
		["name"] = "M-14 Battle Rifle",
		["desc"] = "An M-14 battle rifle.",
		["model"] = "models/halokiller38/fallout/weapons/rifles/trailcarbinescoped.mdl",
		["class"] = "weapon_corder_m14",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_npm60"] = {
		["name"] = "M60",
		["desc"] = "A light M60 with a wooden stock and large belt box.",
		["model"] = "models/weapons/cgc/c_m60_len.mdl",
		["class"] = "weapon_corder_m60",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_corder_lasercannon"] = {	-- Custom order by noctusterrorem#4953
		["name"] = "Sentinel Laser Cannon",
		["desc"] = "A powerful hard-hitting laser cannon that obliterates targets upon direct impact",
		["model"] = "models/falloutweapons/w_fo4instituterif_nope.mdl",
		["class"] = "weapon_corder_lasercannon",
		["ammo"] = "ElectronChargePack",
		["type"] = "energy",
	},
	["weapon_corder_m72"] = {	-- Custom order by noctusterrorem#4953
		["name"] = "M72-P Gauss Rifle",
		["desc"] = "An older prototype variation of the more well known Gauss Rifle. Commonly found within Military installations across the West Coast of the United States.",
		["model"] = "models/fallout/weapons/w_laserscattergun.mdl",
		["class"] = "weapon_corder_m72",
		["ammo"] = "MicrofusionCell",
		["type"] = "energy",
	},
	["weapon_corder_henryrifle"] = {	-- Custom order by Decius#0568
		["name"] = "Henry Rifle",
		["desc"] = "A very powerful and rare Single-shot rifle that chambers .45-70 rounds.",
		["model"] = "models/weapons/cgc/c_henryrifle_len.mdl",
		["class"] = "weapon_corder_henryrifle",
		["ammo"] = "70Govt",
		["type"] = "sniper",
	},
	["weapon_corder_flamerrifle"] = { -- Custom order by Skel0Ton#4463
		["name"] = "Flamer Rifle",
		["desc"] = "BURN, BABY, BURN.",
		["model"] = "models/weapons/cgc/c_flamerrifle_len.mdl",
		["class"] = "weapon_corder_flamerrifle",
		["ammo"] = "none",
		["type"] = "heavy",
	},
	["weapon_corder_mg42"] = {
		["name"] = "MG-42",
		["desc"] = "A general purpose machine gun designed to be low cost and easy to build.",
		["model"] = "models/halokiller38/fallout/weapons/heavy weapons/minigun.mdl",
		["class"] = "weapon_corder_mg42",
		["ammo"] = "556mm",
		["type"] = "rifle",
	},
	["weapon_corder_plasmagauss"] = {
		["name"] = "Plasma Gauss",
		["desc"] = "A modified gauss rifle that shoots plasma-encased bolts.",
		["model"] = "models/halokiller38/fallout/weapons/energy weapons/gaussrifle.mdl",
		["class"] = "weapon_corder_plasmagauss",
		["ammo"] = "MicrofusionCell",
		["powerArmor"] = true,
		["type"] = "energy",
	},
}
